### ISSUE TITLE
Couldn't connect to kvrocks instance

### ISSUE THREAD

**Issue by cuibaiyi** [KvrocksLabs/kvrocks_exporter#1]
**Describe the problem**
runing kvrocks_exporter out Couldn't connect to kvrocks instance!

**version**
kvrocks: 2.0.3
kvrocks_exporter: 1.0.0

**Running the exporter**
./kvrocks_exporter -kvrocks.addr="kvrocks://ip:6666" -kvrocks.password="xxx" 

**Screenshots**
./kvrocks_exporter -kvrocks.addr="kvrocks://ip:6666" -kvrocks.password="xxx" out:
ERRO[0005] Couldn't connect to kvrocks instance

**Comment by git-hulk** [comment]
@cuibaiyi Should be `./kvrocks_exporter -kvrocks.addr="ip:6666" -kvrocks.password="xxx"` if we use the binary.
