### ISSUE TITLE
grafana import 15286 not data!

### ISSUE THREAD

**Issue by cuibaiyi** [KvrocksLabs/kvrocks_exporter#2]
version: grafana v8.2.5

https://grafana.com/grafana/dashboards/15286 import to grafana

Prometheus config
  - job_name: 'kvrocks_exporter'
    static_configs:
      - targets: ['192.168.79.220:9121']

grafana not data
![image](https://user-images.githubusercontent.com/26649998/143562215-598431ea-b1ea-494a-91f4-4771e284fceb.png)

**Comment by git-hulk** [comment]
Can u check whether `http://192.168.79.220:9121/metrics` can get the right data or not?

**Comment by cuibaiyi** [comment]
can.
but grafana version v7.5.11 get data is ok, version v8.2.5 not data

**Comment by git-hulk** [comment]
I may guess the reason, we need to set the Prometheus data source mode to `Browser` after 8.x manually. My bad, I should mention this on the README.

![image](https://user-images.githubusercontent.com/4987594/143569022-fc37ef17-f4d8-4cfa-b1f8-bee52566ba67.png)

**Comment by git-hulk** [comment]
updated README: https://github.com/KvrocksLabs/kvrocks_exporter#for-grafana-8x

**Comment by cuibaiyi** [comment]
After I changed it, I deleted the previous template and re-imported it, but still no data is displayed...
